# Set a plain language title for the site.
title: Philip Levy, Software Design

# Write a short description for the site. This is used for "meta description."
description: Link in bio profile links for connecting and keeping in touch

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Avoid GitHub API authentication when building locally.
github: [metadata]
